### ISSUE TITLE
Where is ~/tools/qemu?

### ISSUE THREAD

**Issue by ap0-0rva** [quic/gunyah-support-scripts#5]
Hi- I am trying to find this directory. It can't be found any where in my root directory.
cd ~/tools/qemu

I found this instead: -
/gunyah/gunyah-support-scripts/scripts/utils$ kern-test.sh

When I run the script, it gives the error: -
./kern-test.sh: line 32: ./bin/qemu-system-aarch64: No such file or directory

**Comment by quic-yvasi** [comment]
Hi Apoorva,

Note that the relevant command needs to be in within the docker environment after launching it. It is indicated by the comment "**All the following commands are run within the docker container**!" right above the section: [test-qemu-and-linux-image](https://github.com/quic/gunyah-support-scripts/blob/develop/quickstart.md#test-qemu-and-linux-image) and it applies to rest of the commands listed on the help.

**Comment by ap0-0rva** [comment]
Got it. I was confused because "Firstly, it's useful to test the QEMU and Linux images without Gunyah" was mentioned, so I assumed you didn't need to be in the Gunyah virtual environment. However, I understand now that you are able to access the directory within the Gunyah venv.
