### ISSUE TITLE
New gunyah patchset v15 breaks build-docker-img.sh, clone-linux-sh

### ISSUE THREAD

**Issue by jglathe** [quic/gunyah-support-scripts#8]
Just noticed while preparing a new round of tests:

![Screenshot from 2023-12-23 10-49-18](https://github.com/quic/gunyah-support-scripts/assets/33185912/592e6eec-8901-4d58-a980-f2d71dc16b00)

shazam appears to grab the newest available patchset, lore.kernel.org/all/20231215-gunyah-v15-0-192a5d872a30@quicinc.com which is not entirely compatible with this kernel (6.5?). I have applied the same patchset in my kernel (6.7-rc6), and I needed some [tweaks](https://github.com/jglathe/linux_ms_dev_kit/commit/aa1a5e12f653a2fea49d625915a4d2f2d59a20b6) to account for some other refactorings that were done.

**Comment by eberman-quic** [comment]
Hi @jglathe,

The series should apply on https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/tag/?h=next-20231215

**Comment by jglathe** [comment]
Thanks. Do I have a chance to actually load the gunyah hypervisor on QCOM hardware? Or is the testable use case qemu on x86-host only?

**Comment by quic-yvasi** [comment]
For now this release only supports qemu on x86 host only. We still didn't release the files/support required for QCom platform. In future we are planning to add support for additional platforms (TBD).

**Comment by jglathe** [comment]
Like sc8280xp based devices? 😼

**Comment by quic-yvasi** [comment]
May be one of our future dragonboards, its not confirmed which one yet.

**Comment by quic-yvasi** [comment]
Looks like the latest version of the patches do not support crosvm. So we need to prevent from applying these latest patches. We need to specify the version to pick. Following seems to work.

-${LINUX_DIR}/tools/b4/b4.sh shazam https://lore.kernel.org/all/20230613172054.3959700-1-quic_eberman@quicinc.com/
+${LINUX_DIR}/tools/b4/b4.sh shazam -v 14 https://lore.kernel.org/all/20230613172054.3959700-1-quic_eberman@quicinc.com/

**Comment by jglathe** [comment]
One finding regarding patchset v15: To build these drivers as modules (which is allowed according to Kconfig) you need an additional export for [anon_inode_getfile_secure](https://github.com/jglathe/linux_ms_dev_kit/commit/efd2e9221626ee29c1a4e1f824ebe37f95197c66).
