### ISSUE TITLE
bashrc-extn permission

### ISSUE THREAD

**Issue by vsrivatsa1** [quic/gunyah-support-scripts#9]
I think we need this fix:

- COPY bashrc-extn .
+ COPY --chown=$USER:$USER bashrc-extn .

Otherwise get this error:

Step 29/30 : RUN cat bashrc-extn >> "${HOME}/.bashrc"  &&  rm -f bashrc-extn
 ---> Running in 15c3e997d384
cat: bashrc-extn: Permission denied
The command '/bin/sh -c cat bashrc-extn >> "${HOME}/.bashrc"  &&  rm -f
bashrc-extn' returned a non-zero code: 1

**Comment by quic-yvasi** [comment]
ah..., sorry, will incorporate this change. soon.

**Comment by quic-yvasi** [comment]
Fixes released in commit 6a959c887f3ccf0396a71f60c25497d99b3efa35
